# travis.yml for github.com/jts/nanopolish

arch:
    - amd64
    - arm64

before_script:
    # Suppress all compiler warnings for hdf5 Makefile
    # to display the log without downloading the raw log on Travis log page.
    # Travis finishs with error when exceeding the limit of 4 MB of log length.
    - export H5_CFLAGS="-w"

script:
    - make && make test
