# travis.yml for github.com/jts/nanopolish

language: generic

matrix:
  include:
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: "CC=gcc-4.9 CXX=g++-4.9 AR=gcc-ar-4.9 NM=gcc-nm-4.9 RANLIB=gcc-ranlib-4.9"
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: "CC=gcc-8 CXX=g++-8 AR=gcc-ar-8 NM=gcc-nm-8 RANLIB=gcc-ranlib-8"
    - os: linux
      arch: arm64
      addons:
        apt:
          packages:
            - libhdf5-serial-dev
      env:
        - HDF5="system"
        - H5_INCLUDE="-I/usr/include/hdf5/serial"
        - LDFLAGS="-L/usr/lib/arm-linux-gnueabihf/hdf5/serial"

before_script:
    # Suppress all compiler warnings for hdf5 Makefile
    # to display the log without downloading the raw log on Travis log page.
    # Travis finishs with error when exceeding the limit of 4 MB of log length.
    - export H5_CFLAGS="-w"
    - dpkg -L libhdf5-dev

script:
    - make && make test
