name: nanopolish

on: [ push ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          submodules: 'true'
        - name: export H5_CFLAGS
          run: export H5_CFLAGS="-w"
        - name: make
          run: export H5_CFLAGS="-w" && make && make test
