name: nanopolish

on: [ push ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        compiler: g++
        g++: 8
        steps:
        - uses: actions/checkout@v2
          #- name: install cppunit
          #- run: sudo apt install -y libcppunit-dev
        - name: make
          run: make
        - name: make test
          run: make test

